server:
  port: ${NOTIFICATION_SERVICE_PORT}

spring:
  application:
    name: notification

eureka:
  instance:
    appname: journal
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    register-with-eureka: true
    fetch-registry: true

rabbitmq:
  queue:
    user-registration:
      name: user.registration.notification
    notification:
      name: notification
