spring:
  application.name: kioke

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false

  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password:

  session:
    store-type: redis
    redis:
      namespace: kioke:session

  threads.virtual.enabled: true

server:
  servlet:
    session:
      cookie:
        path: /
        name: session
        http-only: true
        secure: true
        same-site: none
      timeout: 3600

    multipart:
      enabled: true

s3:
  public:
    endpoint: ${S3_PUBLIC_ENDPOINT}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    bucket: kioke-public

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  metrics:
    export:
      otlp:
        enabled: true
        url: http://localhost:4318/v1/metrics
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
    logs:
      endpoint: http://localhost:4318/v1/logs
  endpoint:
    show-details: always

hibernate:
  generate_statistics: false

logging:
  level:
    io.kioke: DEBUG
    net.ttddyy: DEBUG
