name: ci-java-service
description: Run CI scripts for a Java-based service

inputs:
  service:
    description: The service to run CI scripts for
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run formatter for the service
      uses: axel-op/googlejavaformat-action@v4
      with:
        args: "--replace"
        skip-commit: true
        files: "${{ github.event.inputs.service }}/**/*.java"

    - name: Print changes
      shell: bash
      run: git --no-pager diff --exit-code
