/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Kioke Journal Service
 * OpenAPI spec version: 0.1.0
 */
import type { PagePreviewDto } from './pagePreviewDto';
import type { UserDto } from './userDto';

export interface GetJournalResponseBodyDto {
  journalId?: string;
  title?: string;
  description?: string;
  users?: UserDto[];
  pages?: PagePreviewDto[];
  createdAt?: string;
  lastModified?: string;
  bookmarked?: boolean;
}
