/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Kioke Journal Service
 * OpenAPI spec version: 0.1.0
 */

export interface GetPageResponseBodyDto {
  pageId?: string;
  date?: string;
  title?: string;
  content?: string;
}
