export enum ErrorCode {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  ACCESS_DENIED = 'ACCESS_DENIED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  BAD_CREDENTIALS = 'BAD_CREDENTIALS',
  JOURNAL_NOT_FOUND = 'JOURNAL_NOT_FOUND',
  COLLECTION_NOT_FOUND = 'COLLECTION_NOT_FOUND',
  PAGE_NOT_FOUND = 'PAGE_NOT_FOUND',

  NETWORK_REQUEST_FAILED = 'NETWORK_REQUEST_FAILED',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  JSON_PARSE_FAILED = 'JSON_PARSE_FAILED',
}
